logging:
  level: debug
  format: console
  set_report_caller: true
enable_gin_logger: true
tracing:
  enable: true
  service_name: rec-vendor-api-dev
  collector_fqdn: otel-collector.opentelemetry-operator.svc.cluster.local:4317
  sample_rate: 1
  batch_size: 2000
  max_queue_size: 4000
  batch_timeout: 120s
  excluded_paths:
    - /metrics
    - /healthz
vendor_config:
  {{- with secret "secret/project/recommendation/rec-serving/dev/rec-proxy" }}
  proxy_url: http://{{ .Data.data.user }}:{{ .Data.data.password }}@rec-proxy-smp-prd.arepa.appier.co:3128
  {{- end }}
  timeout: 1s
  vendors:
    - name: linkmine
      request_url: "https://api.linkmine.co.kr/coupang/reco/v2/?app_code=FAXXi4vdOY&device_id={user_id_lower}&device_lmt=0&imp_imageSize={width}x{height}&site_domain={web_host}&app_bundleId={bundle_id}&imp_adType={adtype}"
      tracking_url: "{product_url}&param1={click_id_base64}"
      with_proxy: true
    - name: replace
      request_url: "https://api-gateway.coupang.com/v2/providers/affiliate_open_api/apis/openapi/v1/products/reco?deviceId={user_id_lower}&imageSize={width}x{height}&subId=KRpartner01"
      tracking_url: "https://click.adshot.network/trk?click_id={click_id_base64}&adid={user_id_lower}&land_url={encoded_product_url}"
      {{- with secret "secret/project/recommendation/rec-serving/replace" }}
      access_key: {{ .Data.data.access_key }}
      secret_key: {{ .Data.data.secret_key }}
      {{- end }}
      with_proxy: true
    - name: inl_corp_0
      request_url: "https://adapi.inlcorp.com/cou/api_reco.php?code={size_code}&adid={user_id_lower}&click_id={click_id_base64}"
      tracking_url: "{product_url}"
      with_proxy: true
      size_code_map:
        300x300: 650alldb2
        1200x627: dynamicntdw1
        1200x600: kkobizdw1
    - name: inl_corp_1
      request_url: "https://api.adreload.com/cou/api_reco.php?code={size_code}&adid={user_id_lower}&click_id={click_id_base64}"
      tracking_url: "{product_url}"
      with_proxy: true
      size_code_map:
        300x300: 650alldb2
        1200x627: dynamicntdw1
        1200x600: kkobizdw1
    - name: inl_corp_2
      request_url: "https://api.adiostech.com/cou/api_reco.php?code={size_code}&adid={user_id_lower}&click_id={click_id_base64}"
      tracking_url: "{product_url}"
      with_proxy: true
      size_code_map:
        300x300: 650alldb2
        1200x627: dynamicntdw1
        1200x600: kkobiz1200x600
    - name: inl_corp_3
      request_url: "https://api.ootoo.co.kr/cou/api_reco.php?code={size_code}&type=json&click_log=1&click_id={click_id_base64}&adid={user_id_lower}"
      tracking_url: "{product_url}"
      with_proxy: true
      size_code_map:
        300x300: dlapp4968m
        1200x627: dlapp4968m1200x627
        1200x600: dlapp4968m1200x600
    - name: inl_corp_4
      request_url: "https://cdw.adsrv.co.kr/reco?subId={size_code}&deviceId={user_id_lower}&click_id={click_id_base64}"
      tracking_url: "{product_url}"
      with_proxy: true
      size_code_map:
        300x300: 24650alldb2
        1200x627: 24dynamicntdw1
        1200x600: 24kkobizdw1
    - name: inl_corp_5
      request_url: "https://api.adzet.co.kr/cou/api_reco.php?code=pinpuzzleAPP&adid={user_id_lower}&click_id={click_id_base64}&imageSize={width}x{height}"
      tracking_url: "{product_url}"
      with_proxy: true
    - name: adpopcorn
      request_url: "https://ssp-ext-proxy.adpopcorn.com/coupang/reco?identifier={user_id_lower}&subId=CPSapapp1&imageSize={width}x{height}"
      tracking_url: "{product_url}&subparam={click_id_base64}"
      with_proxy: true
      user_agent: tzyu.net
