logging:
  level: info
  format: json
  set_report_caller: true
enable_gin_logger: true
tracing:
  enable: true
  service_name: rec-vendor-api-stg
  collector_fqdn: otel-collector.opentelemetry-operator.svc.cluster.local:4317
  sample_rate: 1
  batch_size: 2000
  max_queue_size: 4000
  batch_timeout: 120s
  excluded_paths:
    - /metrics
    - /healthz
vendor_config:
  {{- with secret "secret/project/recommendation/rec-serving/staging/rec-proxy" }}
  proxy_url: http://{{ .Data.data.user }}:{{ .Data.data.password }}@rec-proxy-smp-prd-2.arepa.appier.co:3128
  {{- end }}
  timeout: 1s
{{ file "deploy/rec-vendor-api/secrets/vendors.yaml" | indent 2 }}

grpc:
  max_connection_age: 90s
  write_buffer_size_kb: 3
  read_buffer_size_kb: 3